baseURL = 'https://blog.londospark.dev/'
languageCode = 'en-gb'
title = "LondoSpark's Blog"
theme = "terminal"
enableRobotsTXT = true
canonifyURLs = true

[pagination]
pagerSize = 5

[markup.highlight]
noClasses = false

[params]
description = "LondoSpark's personal blog about programming, technology, and other random thoughts."
author = "LondoSpark"
images = ["og-image.png"]
contentTypeName = "posts"
showMenuItems = 2
autoCover = true

[languages]
[languages.en]
languageName = "English"
title = "LondoSpark's Blog"

[languages.en.params]
subtitle = ""
owner = ""
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "LondoSpark's Blog"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
